---
title: "Functions and control flow"
author: "Jonas Schöley"
date: "September 15, 2017"
output:
  html_document:
    toc: no
  github_document:
    toc: no
  pdf_document:
    toc: no
references:
- ISBN: 1-55786-451-9
  author:
  - family: Preston
    given: Samuel
  id: preston2001
  issue: 4
  issued:
    year: 2001
  publisher: Blackwell Publishers
  title: Demography. Measuring and Modeling Population Processes.
  type: book
---

We already know how to calculate a life-table. Below, some familiar code.

```{r}
swe <- read.table('swe_dxnx.txt', skip = 3, header = TRUE)

periods <- unique(swe$period)
age_groups <- unique(swe$age_group)
D <- matrix(swe$deaths, nrow = length(age_groups), dimnames = list(age_groups, periods))
E <- matrix(swe$exposure, nrow = length(age_groups), dimnames = list(age_groups, periods))

x <- c(0, 1, seq(5, 110, 5))
nx <- c(diff(x), Inf)
nmx <- D[,1] / E[,1]
npx <- exp(-nx*nmx)
nqx <- 1-npx
lx <- cumprod(c(1, npx[-length(npx)]))
ndx <- c(diff(-lx), lx[length(lx)])
nLx <- -nx*ndx/log(npx); nLx[is.nan(nLx)] <- 0
Tx <- rev(cumsum(rev(nLx)))
ex <- Tx/lx
```

We can turn this code into a function.

```{r}
LTFun <- function (x, Dx, Nx) {
  nx <- c(diff(x), Inf)
  nmx <- Dx / Nx
  npx <- exp(-nx*nmx)
  nqx <- 1-npx
  lx <- cumprod(c(1, npx[-length(npx)]))
  ndx <- c(diff(-lx), lx[length(lx)])
  nLx <- -nx*ndx/log(npx); nLx[is.nan(nLx)] <- 0
  Tx <- rev(cumsum(rev(nLx)))
  ex <- Tx/lx
  
  data.frame(x, nx, nmx, npx, nqx, lx, ndx, nLx, Tx, ex)
}

LTFun(x = x, Dx = D[,1], Nx = E[,1])
```

A function can only return a single object. If we want to return multiple objects we store them in a single list.

```{r}
LTFun <- function (x, Dx, Nx) {
  nx <- c(diff(x), Inf)
  nmx <- Dx / Nx
  npx <- exp(-nx*nmx)
  nqx <- 1-npx
  lx <- cumprod(c(1, npx[-length(npx)]))
  ndx <- c(diff(-lx), lx[length(lx)])
  nLx <- -nx*ndx/log(npx); nLx[is.nan(nLx)] <- 0
  Tx <- rev(cumsum(rev(nLx)))
  ex <- Tx/lx
  
  list(
    lt = data.frame(x, nx, nmx, npx, nqx, lx, ndx, nLx, Tx, ex),
    summary = c(e0 = ex[[1]], m = x[which.max(ndx)], ltdr = 1/ex[[1]])
  )
}

LTFun(x = x, Dx = D[,1], Nx = E[,1])
```

Once you have written a function it is easy to *iterate* it over your data.

```{r}
lts <- vector(mode = 'list', length = ncol(D))
for (i in 1:ncol(D)) {
  lts[[i]] <- LTFun(x = x, Dx = D[,i], Nx = E[,i])
}
sapply(lts, function (x) {x$summary['e0']})
```